#ifndef PROTO_DEFS_H
#define PROTO_DEFS_H


#define NETPROTOCOL_CONTENT_DELIMETER " "

#define NETPROTOCOL_ID_FIELD_LEN 1
#define NETPROTOCOL_SIZE_FIELD_LEN 4

#define NETPROTOCOL_MAX_CONTENT_LEN 9999

#define NETPROTOCOL_PACKET_ID_INFO   0
#define NETPROTOCOL_PACKET_ID_CMD    1
#define NETPROTOCOL_PACKET_ID_TEMP   3
#define NETPROTOCOL_PACKET_ID_STATUS 4
#define NETPROTOCOL_PACKET_ID_HELLO  5



#endif // PROTO_DEFS_H
